### ISSUE TITLE
</h4> tag alone in Event List widget

### ISSUE THREAD

**Issue by macemmek** [ms-studio/minimalistic-event-manager#13]
In widgets/event-list.php, line 289:
````
<?php echo $mem_event_list[$key]["title"]; ?></h4></a>
````

Isn't that `</h4>` closing tag wrong? Where is it opened?

**Comment by ms-studio** [comment]
Hi @macemmek ,

Well spotted, this is obviously a mistake – a leftover from some other implementation.

Hopefully it didn't break anybody's layout :-0
