### ISSUE TITLE
can's see date fields when creating / editing a post

### ISSUE THREAD

**Issue by slintes** [ms-studio/minimalistic-event-manager#17]
Hey,

I'm running a multisite Wordpress 4.7, just installed and activated your plugin, and can't see any change on the create / edit post page. Should this work on WP 4.7?
If I can help debugging, let me know.

Thx and greetings,

Marc

**Comment by ms-studio** [comment]
Hi @slintes , 

I tested the plugin on several multisite installs in 4.7, the _Event Dates_ metabox is showing up as usual:

<img width="1027" alt="mem-metabox-wp47" src="https://cloud.githubusercontent.com/assets/241637/21289841/4d386ea8-c4a7-11e6-9120-177d87a79c10.png">
 
Did you inspect your

**Comment by slintes** [comment]
I enabled debug and installed "Query Monitor". The only php error is coming from another plugin.
I see that mem.js is called in Chrome developer view.
The only thing which is just not there ist the event date box...

<img width="1349" alt="screen shot 2016-12-18 at 11 08 18" src="https://cloud.githubusercontent.com/assets/1962082/21292863/147f5858-c513-11e6-832f-e97760f17894.png">

(switching to english makes no difference)
I installed the plugin directly from Wordpress... anything which can go wrong there? Worked nice with all other plugins so far.

**Comment by ms-studio** [comment]
That's mysterious indeed. 

May I ask what other plugins you are using on that site?

**Comment by slintes** [comment]
I created a test site where only the mem plugin is activated... no difference.
Then I added some logging to mem.php:
- `mem_plugin_settings` is never called...?
- and probably because of that in `mem_add_metaboxes` the `post_types` array is empty

**Comment by ms-studio** [comment]
About ```mem_plugin_settings()```: this allows to define options in your functions.php file (or using a custom plugin) – [see the documentation](https://github.com/ms-studio/minimalistic-event-manager/wiki/Plugin-options) for an example.

The function ```mem_plugin_settings()``` will be called only if that custom code is used, with the hook called ```mem_init```.

The function that is really critical for displaying the metabox is ```mem_add_metaboxes()```, called on the ```admin_init``` hook.

**Comment by slintes** [comment]
Ok, finally: I added the configuration to functions.php, and now I see the date box :)
But I thought that configuration is optional?

One other question: on the wiki there is a link to a not yet existing page "Output events in iCalendar format". Is that something you're working on?

**Comment by ms-studio** [comment]
Indeed the configuration is optional. Without configuration, the metabox shows up on every content type - supposedly.

The red link in the wiki is there to remind me to write some documentation – I used this feature on some past projects. Here's an exemple from some years ago: https://bitbucket.org/ms-studio/head-construction/src/master/page-ical.php

**Comment by ms-studio** [comment]
And here is a recent implementation I wrote, for an agenda template:

https://bitbucket.org/ms-studio/picto/src/master/page-templates/agenda.php

https://bitbucket.org/ms-studio/picto/src/master/functions/agenda.php

**Comment by slintes** [comment]
without config `mem_add_metaboxes` was called, but the types array was empty. If you want to hunt this further down, let me know if / how I can help.

Thanks for the code examples! I will give the ical implementation a try later on, would be really useful. For an agenda I just the provided widget... good enough for my usecase :) Thanks so far!
