### ISSUE TITLE
Cached/stored post types not getting cleared.

### ISSUE THREAD

**Issue by jerturowetz** [ms-studio/minimalistic-event-manager#18]
I was having some issues with getting this guy to work with my custom post types so I erased all my plugins, switched to twentyseventeen and then did a hard `print_r($post_types);` in mem.php on line 80, just to see what was getting spit out.

And... the plugin is spitting out the post types I removed (and no longer spitting out posts or pages as types either).  I guess they're stored somewhere?

**Comment by ms-studio** [comment]
First, here's the solution to your issue: define the post types you want to be used by the plugin, by using the `mem_plugin_settings()` function (see [Plugin Options](https://github.com/ms-studio/minimalistic-event-manager/wiki/Plugin-options)).

Some explanations: the list of custom post types is saved to an option named 'mem_post_types', at [line 53](https://github.com/ms-studio/minimalistic-event-manager/blob/master/mem.php#L53):

    update_option( 'mem_post_types', $types);

If you _don't_ define that list, it gets populated when the plugin is initialized, at [line 469](https://github.com/ms-studio/minimalistic-event-manager/blob/master/mem.php#L469):

    add_option( 'mem_post_types', $all_post_types);

Note the difference: with `add_option`, if the option already exists, it won't be updated. This explains why you are seeing the post types that you removed.

I hope this helps!

**Comment by jerturowetz** [comment]
Thanks for the quick fix and explanation!  I really appreciate the simplicity (I'm coming from CMB2).
