### ISSUE TITLE
ics/ical export

### ISSUE THREAD

**Issue by pokyah** [ms-studio/minimalistic-event-manager#20]
Hi ms-studio ! 

Thanks for this excellent plugin. 

I'm quite new to php and I get stuck when trying to add a download .ics link next to a post with MEM metakey.

I need this link to appear after the post title when on single post page and also next to post title when in archives lists for example. I'm working on a wordpress genesis theme. I know how to append new items to genesis templates, etc... but I don't know how to handle the variables of MEM to build and generate the well formated string required for the ics format. 

The wiki page for this is not available here on GitHub. 

Any help welcome. 

many thanks

**Comment by ms-studio** [comment]
Hi pokweb,

I'm afraid I don't exactly understand what you need to do.

Regarding the .ics download link... how are you generating the ical/ics file? As you probably noticed, this plugin isn't handling that automatically.
